server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
#      mybatis的foreach必须添加&allowMultiQueries=true
      url: jdbc:mysql://localhost:3306/sx_quzhou?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT&allowMultiQueries=true
      username: root
      password: 123456
      # 配置初始化大小/最大/最小
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#OpenAPI接口配置信息 访问地址 http://ip:port/doc.html
knife4j:
  # 开启增强配置
  enable: true
  basic:
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456
#    enable: true
